// <auto-generated />
namespace ITI.LinkedIn.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addUserProjectEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserProjectEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202002231513553_addUserProjectEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
